#!/bin/bash

set -e

cd $(dirname $0)

echo Compiling typescript
./node_modules/.bin/tsc

echo Marking executable
chmod +x index.js

if [ ! -e bin ]; then
	echo Creating symlink
	mkdir bin
	ln -s `pwd`/index.js `pwd`/bin/elm-make 
else
	echo bin directory already exists
fi
